CREATE TABLE IF NOT EXISTS aggregated_weather_data (
    id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT UUID_GENERATE_V4(),
    city_id UUID NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    humidity INT NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE
);