CREATE TABLE IF NOT EXISTS weather_data (
    id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT UUID_GENERATE_V4(),
    city_id UUID NOT NULL,
    source TEXT NOT NULL,
    temperature DOUBLE PRECISION,
    humidity INT,
    wind_speed DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE
);